In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('../silver/Silver_Video_Games_Sales_as_at_22_Dec_2016.csv')

In [39]:

# Garantir que as colunas de pontuações sejam do tipo numérico
numeric_columns = ["Pontuacao_Critica", "Pontuacao_do_usuario"]
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Preencher pontuações ausentes com a média das existentes
df["Pontuacao_Critica"].fillna(df["Pontuacao_Critica"].mean(), inplace=True)
df["Pontuacao_do_usuario"].fillna(df["Pontuacao_do_usuario"].mean(), inplace=True)

C:\Users\Avila\AppData\Local\Temp\ipykernel_6940\1671510855.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Pontuacao_Critica"].fillna(df["Pontuacao_Critica"].mean(), inplace=True)
C:\Users\Avila\AppData\Local\Temp\ipykernel_6940\1671510855.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Pontuacao_do_usuario"].fillna(df["Pontuacao_do_usuario"].mean(), inplace=True)

In [40]:
# 2. Padronização de categorias
df["Genero"] = df["Genero"].str.capitalize()

In [41]:
# Faixa Etária
df["Faixa_Etaria"] = np.where(df["Classificacao"] == "Livre", "Todos", "Restrito")

# Sucesso Comercial
df["Sucesso_Comercial"] = np.select(
    [
        df["Vendas_Globais"] > 50,
        df["Vendas_Globais"] > 20
    ],
    ["Alto", "Médio"],
    default="Baixo"
)

In [42]:
# Cálculo de percentuais regionais
df["Percentual_NA"] = (df["NA_Vendas"] / df["Vendas_Globais"]) * 100
df["Percentual_EU"] = (df["EU_Vendas"] / df["Vendas_Globais"]) * 100
df["Percentual_JP"] = (df["JP_Vendas"] / df["Vendas_Globais"]) * 100
df["Percentual_Outras"] = (df["Outras_Vendas"] / df["Vendas_Globais"])

In [43]:
# 5. Ranking por Gênero
df["Ranking_Genero"] = df.groupby("Genero")["Vendas_Globais"].rank(ascending=False, method="min")

In [44]:
# Exibir DataFrame final
print("Dados refinados para camada Gold:")
print(df.head())

Dados refinados para camada Gold:
                  Nome_Jogo Plataforma  Ano_de_Lancamento      Genero  \
0                Wii Sports        Wii               2006     Esporte
1         Super Mario Bros.        NES               1985  Plataforma
2            Mario Kart Wii        Wii               2008     Corrida
3         Wii Sports Resort        Wii               2009     Esporte
4  Pokemon Red/Pokemon Blue         GB               1996         Rpg

    Editora  NA_Vendas  EU_Vendas  JP_Vendas  Outras_Vendas  Vendas_Globais  \
0  Nintendo      41.36      28.96       3.77           8.45           82.53
1  Nintendo      29.08       3.58       6.81           0.77           40.24
2  Nintendo      15.68      12.76       3.79           3.29           35.52
3  Nintendo      15.61      10.93       3.28           2.95           32.77
4  Nintendo      11.27       8.89      10.22           1.00           31.37

   ...  Contagem_de_usuarios  Desenvolvedor  Classificacao  Faixa_Etaria  \
0  ...                   322       Nintendo          Livre         Todos
1  ...                     0   Nao_Inserido   Nao_Inserido      Restrito
2  ...                   709       Nintendo          Livre         Todos
3  ...                   192       Nintendo          Livre         Todos
4  ...                     0   Nao_Inserido   Nao_Inserido      Restrito

  Sucesso_Comercial Percentual_NA Percentual_EU Percentual_JP  \
0              Alto     50.115110     35.090270      4.568036
1             Médio     72.266402      8.896620     16.923459
2             Médio     44.144144     35.923423     10.670045
3             Médio     47.635032     33.353677     10.009155
4             Médio     35.926044     28.339178     32.578897

   Percentual_Outras  Ranking_Genero
0           0.102387             1.0
1           0.019135             1.0
2           0.092624             1.0
3           0.090021             2.0
4           0.031878             1.0

[5 rows x 23 columns]

In [45]:
df.head(5)

,Nome_Jogo,Plataforma,Ano_de_Lancamento,Genero,Editora,NA_Vendas,EU_Vendas,JP_Vendas,Outras_Vendas,Vendas_Globais,...,Contagem_de_usuarios,Desenvolvedor,Classificacao,Faixa_Etaria,Sucesso_Comercial,Percentual_NA,Percentual_EU,Percentual_JP,Percentual_Outras,Ranking_Genero
0,Wii Sports,Wii,2006,Esporte,Nintendo,41.36,28.96,3.77,8.45,82.53,...,322,Nintendo,Livre,Todos,Alto,50.115110,35.090270,4.568036,0.102387,1.0
1,Super Mario Bros.,NES,1985,Plataforma,Nintendo,29.08,3.58,6.81,0.77,40.24,...,0,Nao_Inserido,Nao_Inserido,Restrito,Médio,72.266402,8.896620,16.923459,0.019135,1.0
2,Mario Kart Wii,Wii,2008,Corrida,Nintendo,15.68,12.76,3.79,3.29,35.52,...,709,Nintendo,Livre,Todos,Médio,44.144144,35.923423,10.670045,0.092624,1.0
3,Wii Sports Resort,Wii,2009,Esporte,Nintendo,15.61,10.93,3.28,2.95,32.77,...,192,Nintendo,Livre,Todos,Médio,47.635032,33.353677,10.009155,0.090021,2.0
4,Pokemon Red/Pokemon Blue,GB,1996,Rpg,Nintendo,11.27,8.89,10.22,1.00,31.37,...,0,Nao_Inserido,Nao_Inserido,Restrito,Médio,35.926044,28.339178,32.578897,0.031878,1.0

In [ ]:
df.to_csv('gold_Video_Games_Sales_as_at_22_Dec_2016.csv', index=False)